---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "userNamespaceOperator.name" . }}
  labels:
    {{- include "userNamespaceOperator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - usernamespace.gpte.redhat.com
  resources:
  - usernamespaces
  - usernamespaces/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - usernamespace.gpte.redhat.com
  resources:
  - usernamespaceconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - usernamespace.gpte.redhat.com
  resources:
  - usernamespaceconfigs/status
  verbs:
  - patch
  - update
- apiGroups:
  - template.openshift.io
  resources:
  - templates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - template.openshift.io
  resources:
  - processedtemplates
  verbs:
  - create
- apiGroups:
  - user.openshift.io
  resources:
  - groups
  - users
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - project.openshift.io
  resources:
  - projectrequests
  verbs:
  - create
- apiGroups:
  - ''
  resources:
  - namespaces
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
{{ if .Values.clusterRole.clusterAdmin -}}
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
{{ end -}}
