{{- if .Values.defaultUserNamespaceConfig.create }}
---
apiVersion: usernamespace.gpte.redhat.com/v1
kind: UserNamespaceConfig
metadata:
  name: default
spec:
  {{- if .Values.defaultUserNamespaceConfig.autocreate.enable }}
  autocreate:
    description: {{ quote .Values.defaultUserNamespaceConfig.autocreate.description }}
    displayName: {{ quote .Values.defaultUserNamespaceConfig.autocreate.displayName }}
    enable: true
    prefix: {{ .Values.defaultUserNamespaceConfig.autocreate.prefix }}
  {{- end }}
  roleBindings:
    {{- toYaml .Values.defaultUserNamespaceConfig.roleBindings | nindent 4 }}
{{- end }}
