{{- if .Values.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "userNamespaceOperator.namespaceName" . }}
  labels:
    {{- include "userNamespaceOperator.labels" . | nindent 4 }}
{{- end -}}
