apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: usernamespaces.usernamespace.gpte.redhat.com
spec:
  group: usernamespace.gpte.redhat.com
  scope: Cluster
  names:
    plural: usernamespaces
    singular: usernamespace
    kind: UserNamespace
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        description: >-
          User namespace request.
        type: object
        required:
        - apiVersion
        - kind
        - metadata
        - spec
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
            properties:
              name:
                type: string
                maxLength: 63
                pattern: ^[a-z0-9A-Z]([a-z0-9A-Z\-]*[a-z0-9A-Z])?$
          spec:
            description: >-
              Definition of the UserNamespace request.
            type: object
            required:
            - user
            properties:
              config:
                description: >-
                  Reference to UserNamespaceConfig related to this UserNamespace.
                type: object
                required:
                - apiVersion
                - kind
                - name
                - uid
                properties:
                  apiVersion:
                    type: string
                    enum:
                    - usernamespace.gpte.redhat.com/v1
                  kind:
                    type: string
                    enum:
                    - UserNamespaceConfig
                  name:
                    type: string
                  uid:
                    type: string
              description:
                description: >-
                  Content for namespace "openshift.io/description" annotation.
                displayName: >-
                  Content for namespace "openshift.io/display-name" annotation.
                type: string
              displayName:
                type: string
              user:
                description: >-
                  Reference to user for whom a namespace is requested.
                type: object
                required:
                - apiVersion
                - kind
                - name
                - uid
                properties:
                  apiVersion:
                    type: string
                    enum:
                    - user.openshift.io/v1
                  kind:
                    type: string
                    enum:
                    - User
                  name:
                    type: string
                  uid:
                    type: string
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              managedResources:
                description: >-
                  List of resources managed for the namespace.
                type: array
                items:
                  type: object
                  requeired:
                  - apiVersion
                  - kind
                  - name
                  properties:
                    apiVersion:
                      type: string
                    kind:
                      type: string
                    name:
                      type: string
                    namespace:
                      type: string
