---
name: pull-request
on:
  pull_request:
    branches:
    - main
jobs:
  test:
    env:
      IMAGE_NAME: user-namespace-operator
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@master

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    #- name: Static tests
    #  run: |

    - name: Build image
      uses: docker/build-push-action@v2
      with:
        push: false
        repository: user-namespace-operator
        tags: ${{ steps.check_version.outputs.VERSION }}

    - name: Build test image
      uses: docker/build-push-action@v2
      with:
        push: false
        repository: ${{ env.IMAGE_NAME }}
        tags: ${{ github.sha }}

    #- name: Test image
    #  run: |
